openapi: 3.0.3
info:
  title: API Specifications
  description: API Specifications
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
    description: 'Local server'
paths:
  /home:
    get:
      description: Test endpoint
      responses:
        200:
          description: Test response
          content:
            application/json:
              schema:
                type: object
                items:
                  test:
                  type: string